name: PPUU
channels:
  - pytorch
  - defaults
dependencies:
  - imageio
  - pandas
  - python=3.7
  - pytorch=1.2.0
  - scipy=1.2.0
  - matplotlib
  - pip
  - jupyter
  - scikit-learn
  - scikit-image
  - pip:
    - gym
    - pygame
    - jupytext
    - ipdb
    - tb-nightly
    - moviepy
    - bqplot
